CREATE TABLE users
(
    id BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDb;

CREATE TABLE services
(
    id BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    service_name VARCHAR(255) NOT NULL
) ENGINE = InnoDb;

CREATE TABLE customers
(
    id BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    service_id BIGINT(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    address LONGTEXT NOT NULL,
    post_code VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (service_id) REFERENCES services(id)
) ENGINE = InnoDb;